import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Tipos TypeScript generados desde la base de datos
export type Database = {
  public: {
    Tables: {
      empresas: {
        Row: {
          id: string;
          nombre: string;
          nit: string | null;
          direccion: string | null;
          telefono: string | null;
          email: string | null;
          descripcion: string | null;
          sitio_web: string | null;
          industria: string | null;
          configuracion: any;
          estado: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          nombre: string;
          nit?: string | null;
          direccion?: string | null;
          telefono?: string | null;
          email?: string | null;
          descripcion?: string | null;
          sitio_web?: string | null;
          industria?: string | null;
          configuracion?: any;
          estado?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          nombre?: string;
          nit?: string | null;
          direccion?: string | null;
          telefono?: string | null;
          email?: string | null;
          descripcion?: string | null;
          sitio_web?: string | null;
          industria?: string | null;
          configuracion?: any;
          estado?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      usuarios: {
        Row: {
          id: string;
          empresa_id: string;
          tipo_usuario_id: string | null;
          nombre: string;
          apellidos: string | null;
          email: string;
          telefono: string | null;
          tipo_documento: string;
          numero_documento: string | null;
          fecha_nacimiento: string | null;
          genero: string;
          direccion: string | null;
          ciudad: string | null;
          estado_region: string | null;
          pais: string;
          contacto_emergencia_nombre: string | null;
          contacto_emergencia_telefono: string | null;
          contacto_emergencia_relacion: string | null;
          tipo_sangre: string | null;
          alergias: string | null;
          medicamentos_actuales: string | null;
          condiciones_medicas: string | null;
          notas_medicas: string | null;
          fecha_ultimo_chequeo: string | null;
          personal_preferido_id: string | null;
          horario_preferido: string | null;
          preferencias_comunicacion: string[];
          idioma_preferido: string;
          consentimiento_privacidad: boolean;
          consentimiento_marketing: boolean;
          notas: string | null;
          estado: string;
          ultimo_acceso: string | null;
          total_citas: number;
          citas_completadas: number;
          citas_canceladas: number;
          total_gastado: number;
          calificacion_promedio: number | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          tipo_usuario_id?: string | null;
          nombre: string;
          apellidos?: string | null;
          email: string;
          telefono?: string | null;
          tipo_documento?: string;
          numero_documento?: string | null;
          fecha_nacimiento?: string | null;
          genero?: string;
          direccion?: string | null;
          ciudad?: string | null;
          estado_region?: string | null;
          pais?: string;
          contacto_emergencia_nombre?: string | null;
          contacto_emergencia_telefono?: string | null;
          contacto_emergencia_relacion?: string | null;
          tipo_sangre?: string | null;
          alergias?: string | null;
          medicamentos_actuales?: string | null;
          condiciones_medicas?: string | null;
          notas_medicas?: string | null;
          fecha_ultimo_chequeo?: string | null;
          personal_preferido_id?: string | null;
          horario_preferido?: string | null;
          preferencias_comunicacion?: string[];
          idioma_preferido?: string;
          consentimiento_privacidad?: boolean;
          consentimiento_marketing?: boolean;
          notas?: string | null;
          estado?: string;
          ultimo_acceso?: string | null;
          total_citas?: number;
          citas_completadas?: number;
          citas_canceladas?: number;
          total_gastado?: number;
          calificacion_promedio?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          tipo_usuario_id?: string | null;
          nombre?: string;
          apellidos?: string | null;
          email?: string;
          telefono?: string | null;
          tipo_documento?: string;
          numero_documento?: string | null;
          fecha_nacimiento?: string | null;
          genero?: string;
          direccion?: string | null;
          ciudad?: string | null;
          estado_region?: string | null;
          pais?: string;
          contacto_emergencia_nombre?: string | null;
          contacto_emergencia_telefono?: string | null;
          contacto_emergencia_relacion?: string | null;
          tipo_sangre?: string | null;
          alergias?: string | null;
          medicamentos_actuales?: string | null;
          condiciones_medicas?: string | null;
          notas_medicas?: string | null;
          fecha_ultimo_chequeo?: string | null;
          personal_preferido_id?: string | null;
          horario_preferido?: string | null;
          preferencias_comunicacion?: string[];
          idioma_preferido?: string;
          consentimiento_privacidad?: boolean;
          consentimiento_marketing?: boolean;
          notas?: string | null;
          estado?: string;
          ultimo_acceso?: string | null;
          total_citas?: number;
          citas_completadas?: number;
          citas_canceladas?: number;
          total_gastado?: number;
          calificacion_promedio?: number | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      google_calendars: {
        Row: {
          id: string;
          empresa_id: string;
          usuario_id: string;
          google_calendar_id: string;
          nombre: string;
          descripcion: string | null;
          color: string;
          zona_horaria: string;
          es_principal: boolean;
          sincronizacion_activa: boolean;
          direccion_sincronizacion: string;
          ultimo_sync: string | null;
          access_token: string | null;
          refresh_token: string | null;
          token_expiry: string | null;
          configuracion: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          usuario_id: string;
          google_calendar_id: string;
          nombre: string;
          descripcion?: string | null;
          color?: string;
          zona_horaria?: string;
          es_principal?: boolean;
          sincronizacion_activa?: boolean;
          direccion_sincronizacion?: string;
          ultimo_sync?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expiry?: string | null;
          configuracion?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          usuario_id?: string;
          google_calendar_id?: string;
          nombre?: string;
          descripcion?: string | null;
          color?: string;
          zona_horaria?: string;
          es_principal?: boolean;
          sincronizacion_activa?: boolean;
          direccion_sincronizacion?: string;
          ultimo_sync?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expiry?: string | null;
          configuracion?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      citas: {
        Row: {
          id: string;
          empresa_id: string;
          cliente_id: string;
          personal_id: string | null;
          servicio_id: string;
          sucursal_id: string;
          google_calendar_id: string | null;
          google_event_id: string | null;
          fecha: string;
          hora: string;
          duracion: number;
          estado: string;
          canal: string;
          origen: string;
          notas: string | null;
          precio_acordado: number | null;
          estado_pago: string;
          medio_pago: string | null;
          recordatorios_enviados: any;
          metadata: any;
          sync_status: string;
          sync_error: string | null;
          last_sync: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          cliente_id: string;
          personal_id?: string | null;
          servicio_id: string;
          sucursal_id: string;
          google_calendar_id?: string | null;
          google_event_id?: string | null;
          fecha: string;
          hora: string;
          duracion?: number;
          estado?: string;
          canal?: string;
          origen?: string;
          notas?: string | null;
          precio_acordado?: number | null;
          estado_pago?: string;
          medio_pago?: string | null;
          recordatorios_enviados?: any;
          metadata?: any;
          sync_status?: string;
          sync_error?: string | null;
          last_sync?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          cliente_id?: string;
          personal_id?: string | null;
          servicio_id?: string;
          sucursal_id?: string;
          google_calendar_id?: string | null;
          google_event_id?: string | null;
          fecha?: string;
          hora?: string;
          duracion?: number;
          estado?: string;
          canal?: string;
          origen?: string;
          notas?: string | null;
          precio_acordado?: number | null;
          estado_pago?: string;
          medio_pago?: string | null;
          recordatorios_enviados?: any;
          metadata?: any;
          sync_status?: string;
          sync_error?: string | null;
          last_sync?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      google_events: {
        Row: {
          id: string;
          google_calendar_id: string;
          cita_id: string | null;
          google_event_id: string;
          titulo: string;
          descripcion: string | null;
          fecha_inicio: string;
          fecha_fin: string;
          zona_horaria: string;
          es_todo_el_dia: boolean;
          ubicacion: string | null;
          estado: string;
          visibilidad: string;
          asistentes: any;
          recordatorios: any;
          recurrencia: any | null;
          metadata_google: any;
          sync_status: string;
          sync_direction: string;
          last_modified: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          google_calendar_id: string;
          cita_id?: string | null;
          google_event_id: string;
          titulo: string;
          descripcion?: string | null;
          fecha_inicio: string;
          fecha_fin: string;
          zona_horaria?: string;
          es_todo_el_dia?: boolean;
          ubicacion?: string | null;
          estado?: string;
          visibilidad?: string;
          asistentes?: any;
          recordatorios?: any;
          recurrencia?: any | null;
          metadata_google?: any;
          sync_status?: string;
          sync_direction?: string;
          last_modified?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          google_calendar_id?: string;
          cita_id?: string | null;
          google_event_id?: string;
          titulo?: string;
          descripcion?: string | null;
          fecha_inicio?: string;
          fecha_fin?: string;
          zona_horaria?: string;
          es_todo_el_dia?: boolean;
          ubicacion?: string | null;
          estado?: string;
          visibilidad?: string;
          asistentes?: any;
          recordatorios?: any;
          recurrencia?: any | null;
          metadata_google?: any;
          sync_status?: string;
          sync_direction?: string;
          last_modified?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};